version: "2"
services:
  web:
    build: .
    ports:
    - "3900:3900"
    depends_on:
    - mongo
  mongo:
    image: mongo:4.2.10
    ports:
    - "27017:27017"
    volumes:
      - ./data:/data/db